api_version: 1
runtime: custom
vm:      true

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 20
  cool_down_period_sec: 330
  cpu_utilization:
    target_utilization: 0.5
  
resources:
  cpu: 1
  memory_gb: 3.75
  disk_size_gb: 10
    
health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 15

network:
  forwarded_ports:
  - 5005
  
